version: '3.8'
name: ematerai_frontend
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    dns: 8.8.8.8
    environment:
      - NEXT_PUBLIC_API_HOST=192.168.6.87
      - NEXT_PUBLIC_API_PORT=5000
      - NEXT_PUBLIC_API_PORT_FE=3000
      - NEXT_PUBLIC_X_API_KEY=e6a637643ca02f19580e14895664d470
      - NEXT_PUBLIC_CONS_ID=39205596
      - NEXT_PUBLIC_BACKEND_HOST=http://192.168.6.87:5000

    networks:
      - ematerai_FE_network
    stdin_open: true
    tty: true
    restart: always
    command: ["npx", "next", "start", "-p", "3000", "-H", "0.0.0.0"]

networks:
  ematerai_FE_network:
    name: ematerai_FE_network
    driver: bridge
